- name: This is a hello-world example
  hosts: webservers
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt

    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        src:  /etc/hosts
        dest: /tmp/testfile2.txt